/** 委托页静态资源路径（public/assets/entrust） */
export const entrustAssets = {
  logo: "/assets/entrust/logo.png",
  langIcon: "/assets/entrust/lang-icon.svg",
  walletDot: "/assets/entrust/wallet-dot.svg",
  ticketIcon: "/assets/entrust/ticket-small.png",
  hot: "/assets/entrust/hot.png",
  rulesArrow: "/assets/entrust/rules-arrow.png",
  btnWhitelist: "/assets/entrust/btn-whitelist.png",
  ticketDeco: "/assets/entrust/ticket-deco.png",
  announcementIcon: "/assets/entrust/announcement-megaphone.png",
  announcementWindowFrame: "/assets/entrust/announcement-window-frame.png",
  announcementWindowFrameOverlay:
    "/assets/entrust/announcement-window-frame-overlay.png",
  projectBanner: "/assets/entrust/project-banner.png",
  startAiBanner: "/assets/entrust/start-ai-banner.png",
  chartFill: "/assets/entrust/chart-fill.png",
  chartLine: "/assets/entrust/chart-line.png",
  chartDot: "/assets/entrust/chart-dot.png",
  dividerLine: "/assets/entrust/divider-line.png",
  btnStart: "/assets/entrust/btn-start.png",
  strategyTrend: "/assets/entrust/strategy-trend.png",
  strategyArbitrage: "/assets/entrust/strategy-arbitrage.png",
  strategyHedge: "/assets/entrust/strategy-hedge.png",
  deployUsdtIcon: "/assets/entrust/custody-usdt-icon.png",
  aiDepositIcon: "/assets/entrust/ai-deposit-icon.png",
  aiEarningsIcon: "/assets/entrust/ai-earnings-icon.png",
  navEntrust: "/assets/entrust/nav-entrust.png",
  navEarnings: "/assets/entrust/nav-earnings.svg",
  navMine: "/assets/entrust/nav-mine.svg",
  navTeam: "/assets/entrust/nav-team.svg",
  projectsHeroBg: "/assets/entrust/projects/projects-hero-bg.png",
  projectsFeatureAgentIcon:
    "/assets/entrust/projects/projects-feature-agent-icon.png",
  projectsFeatureAgentCircle:
    "/assets/entrust/projects/projects-feature-agent-circle.svg",
  projectsFeatureAgentCube:
    "/assets/entrust/projects/projects-feature-agent-cube.png",
  projectsFeatureAgent: "/assets/entrust/projects/projects-feature-agent.png",
  projectsFeatureValue: "/assets/entrust/projects/projects-feature-value.png",
  projectsRoleUser: "/assets/entrust/projects/projects-role-user.png",
  projectsRoleBrain: "/assets/entrust/projects/projects-role-brain.png",
  projectsRoleOs: "/assets/entrust/projects/projects-role-os.png",
  projectsSocialYoutube: "/assets/entrust/projects/projects-social-youtube.png",
  projectsSocialX: "/assets/entrust/projects/projects-social-x.png",
  projectsSocialTelegram: "/assets/entrust/projects/projects-social-telegram.png",
  projectsSocialParagraph: "/assets/entrust/projects/projects-social-paragraph.png",
  projectsSocialDapp: "/assets/entrust/projects/projects-social-dapp.png",
  projectsSocialLinktree: "/assets/entrust/projects/projects-social-linktree.png",
  projectsAboutDrive: "/assets/entrust/projects/projects-about-drive.png",
  projectsAboutNotion: "/assets/entrust/projects/projects-about-notion.png",
} as const;
