/** 委托页静态资源路径（public/assets/entrust） */
export const entrustAssets = {
  logo: "/assets/entrust/logo.png",
  langGlow: "/assets/entrust/lang-glow.svg",
  langIcon: "/assets/entrust/lang-icon.svg",
  walletDot: "/assets/entrust/wallet-dot.svg",
  ticketIcon: "/assets/entrust/ticket-small.png",
  hot: "/assets/entrust/hot.png",
  rulesArrow: "/assets/entrust/rules-arrow.svg",
  btnWhitelist: "/assets/entrust/btn-whitelist.svg",
  ticketDeco: "/assets/entrust/ticket-deco.png",
  projectBanner: "/assets/entrust/project-banner.png",
  projectGlow: "/assets/entrust/project-glow.svg",
  startAiBanner: "/assets/entrust/start-ai-banner.png",
  chartFill: "/assets/entrust/chart-fill.svg",
  chartLine: "/assets/entrust/chart-line.svg",
  chartDot: "/assets/entrust/chart-dot.svg",
  dividerLine: "/assets/entrust/divider-line.svg",
  btnStart: "/assets/entrust/btn-start.svg",
  strategyTrend: "/assets/entrust/strategy-trend.svg",
  strategyArbitrage: "/assets/entrust/strategy-arbitrage.svg",
  strategyHedge: "/assets/entrust/strategy-hedge.svg",
  navEntrust: "/assets/entrust/nav-entrust.png",
  navEarnings: "/assets/entrust/nav-earnings.svg",
  navMine: "/assets/entrust/nav-mine.svg",
  navTeam: "/assets/entrust/nav-team.svg",
} as const;
