/** 委托页静态资源路径（public/assets/entrust） */
export const entrustAssets = {
  logo: "/assets/entrust/logo.png",
  langIcon: "/assets/entrust/lang-icon.svg",
  walletDot: "/assets/entrust/wallet-dot.svg",
  ticketIcon: "/assets/entrust/ticket-small.png",
  hot: "/assets/entrust/hot.png",
  rulesArrow: "/assets/entrust/rules-arrow.svg",
  btnWhitelist: "/assets/entrust/btn-whitelist.svg",
  ticketDeco: "/assets/entrust/ticket-deco.png",
  projectBanner: "/assets/entrust/project-banner.png",
  projectGlow: "/assets/entrust/project-glow.svg",
  startAiBanner: "/assets/entrust/start-ai-banner.png",
  chartFill: "/assets/entrust/chart-fill.svg",
  chartLine: "/assets/entrust/chart-line.svg",
  chartDot: "/assets/entrust/chart-dot.svg",
  dividerLine: "/assets/entrust/divider-line.svg",
  btnStart: "/assets/entrust/btn-start.svg",
  strategyTrend: "/assets/entrust/strategy-trend.svg",
  strategyArbitrage: "/assets/entrust/strategy-arbitrage.svg",
  strategyHedge: "/assets/entrust/strategy-hedge.svg",
  navEntrust: "/assets/entrust/nav-entrust.png",
  navEarnings: "/assets/entrust/nav-earnings.svg",
  navMine: "/assets/entrust/nav-mine.svg",
  navTeam: "/assets/entrust/nav-team.svg",
  projectsHeroBg: "/assets/entrust/projects/projects-hero-bg.png",
  projectsFeatureAgentIcon:
    "/assets/entrust/projects/projects-feature-agent-icon.png",
  projectsFeatureAgentCircle:
    "/assets/entrust/projects/projects-feature-agent-circle.svg",
  projectsFeatureAgentCube:
    "/assets/entrust/projects/projects-feature-agent-cube.png",
  projectsFeatureAgent: "/assets/entrust/projects/projects-feature-agent.png",
  projectsFeatureValue: "/assets/entrust/projects/projects-feature-value.png",
  projectsRoleUser: "/assets/entrust/projects/projects-role-user.png",
  projectsRoleBrain: "/assets/entrust/projects/projects-role-brain.png",
  projectsRoleOs: "/assets/entrust/projects/projects-role-os.png",
  projectsSocialYoutube: "/assets/entrust/projects/projects-social-youtube.png",
  projectsSocialX: "/assets/entrust/projects/projects-social-x.png",
  projectsSocialParagraph: "/assets/entrust/projects/projects-social-paragraph.png",
  projectsSocialLinktree: "/assets/entrust/projects/projects-social-linktree.png",
  projectsAboutDrive: "/assets/entrust/projects/projects-about-drive.png",
  projectsAboutNotion: "/assets/entrust/projects/projects-about-notion.png",
} as const;
