/** 我的页静态资源（public/assets/mine） */
export const mineAssets = {
  assetCardBg: "/assets/mine/asset-card-bg.png",
  actionUsdt: "/assets/mine/action-usdt.png",
  actionAul: "/assets/mine/action-aul.png",
  actionInvest: "/assets/mine/action-invest.png",
  inviteBannerBg: "/assets/mine/invite-banner-bg.png",
  swapBannerBg: "/assets/mine/swap-banner-bg.png",
  /** Figma 943:1561 原图，容器内百分比裁切 */
  swapHeroBgSource: "/assets/mine/swap-hero-bg-source.png",
  swapHeroIp: "/assets/mine/swap-hero-ip.png",
  swapFillMax: "/assets/mine/swap-fill-max.svg",
  swapToggle: "/assets/mine/swap-toggle.png",
  swapAulToken: "/assets/mine/swap-aul-token.png",
  swapUsdtToken: "/assets/mine/swap-usdt-token.svg",
  inviteSheetIllustration: "/assets/mine/invite-sheet-illustration.png",
  inviteSheetQr: "/assets/mine/invite-sheet-qr.png",
  inviteSheetCopy: "/assets/mine/invite-sheet-copy.svg",
  inviteSheetClose: "/assets/mine/invite-sheet-close.svg",
  fundIcon: "/assets/mine/fund-icon.png",
  statDividerV: "/assets/mine/stat-divider-v.svg",
  fundDividerH: "/assets/mine/fund-divider-h.svg",
  fundDividerRow: "/assets/mine/fund-divider-row.svg",
  chevronDown: "/assets/mine/chevron-down.svg",
  pageChevronLeft: "/assets/mine/page-chevron-left.svg",
  pageChevronRight: "/assets/mine/page-chevron-right.svg",
  pageEllipsis: "/assets/mine/page-ellipsis.svg",
  withdrawUsdtIcon: "/assets/mine/withdraw-usdt-icon.svg",
  withdrawAulIcon: "/assets/mine/withdraw-aul-icon.png",
  withdrawInputDivider: "/assets/mine/withdraw-input-divider.svg",
  summaryUsdtWithdrawable: "/assets/mine/summary-usdt-withdrawable.png",
  summaryAulWithdrawable: "/assets/mine/summary-aul-withdrawable.png",
  summaryTotalEntrust: "/assets/mine/summary-total-entrust.png",
  summaryAulUnreleased: "/assets/mine/summary-aul-unreleased.png",
} as const;
